import smtplib
import json
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import List, Dict, Optional

class EmailManager:
    def __init__(self, email: Optional[str] = None, password: Optional[str] = None):
        """Initialize email manager"""
        self.email = email or os.getenv("JARVIS_EMAIL")
        self.password = password or os.getenv("JARVIS_EMAIL_PASSWORD")
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587
    
    def send_email(self, to: str, subject: str, body: str, is_html: bool = False) -> bool:
        """Send an email"""
        if not self.email or not self.password:
            print("[EMAIL] Error: Email credentials not configured")
            return False
        
        try:
            msg = MIMEMultipart()
            msg['From'] = self.email
            msg['To'] = to
            msg['Subject'] = subject
            
            if is_html:
                msg.attach(MIMEText(body, 'html'))
            else:
                msg.attach(MIMEText(body, 'plain'))
            
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(self.email, self.password)
            server.send_message(msg)
            server.quit()
            
            print(f"[EMAIL] Sent to {to}: {subject}")
            return True
        except Exception as e:
            print(f"[EMAIL] Error sending email: {e}")
            return False
    
    def send_todo_summary(self, to: str, todos: List[Dict]) -> bool:
        """Send todo summary email"""
        pending = [t for t in todos if not t['completed']]
        completed = [t for t in todos if t['completed']]
        
        html = f"""
        <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; background: #05070b; color: #00e5ff; }}
                    .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
                    h1 {{ color: #00e5ff; text-align: center; }}
                    .section {{ margin: 20px 0; }}
                    .pending {{ border-left: 4px solid #ff0033; padding: 10px; }}
                    .completed {{ border-left: 4px solid #00cc33; padding: 10px; opacity: 0.7; }}
                    .task {{ margin: 10px 0; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>📋 JARVIS Todo Summary</h1>
                    <div class="section">
                        <h2>Pending Tasks ({len(pending)})</h2>
                        <div>
                            {''.join([f'<div class="task pending">{t["title"]}</div>' for t in pending])}
                        </div>
                    </div>
                    <div class="section">
                        <h2>Completed Tasks ({len(completed)})</h2>
                        <div>
                            {''.join([f'<div class="task completed">✓ {t["title"]}</div>' for t in completed])}
                        </div>
                    </div>
                    <p style="text-align: center; color: #00e5ff99;">Generated by JARVIS at {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
                </div>
            </body>
        </html>
        """
        
        return self.send_email(to, "📋 Your Todo Summary", html, is_html=True)
    
    def send_weather_alert(self, to: str, weather: Dict) -> bool:
        """Send weather alert email"""
        html = f"""
        <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; background: #05070b; color: #00e5ff; }}
                    .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
                    h1 {{ color: #00e5ff; text-align: center; }}
                    .weather-info {{ background: #10141c; border: 1px solid #00e5ff33; padding: 20px; border-radius: 5px; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>🌤️ Weather Alert</h1>
                    <div class="weather-info">
                        <h2>{weather.get('city', 'Unknown')}, {weather.get('country', '')}</h2>
                        <p><strong>Temperature:</strong> {weather.get('temp', 'N/A')}°C</p>
                        <p><strong>Feels Like:</strong> {weather.get('feels_like', 'N/A')}°C</p>
                        <p><strong>Condition:</strong> {weather.get('description', 'N/A')}</p>
                        <p><strong>Humidity:</strong> {weather.get('humidity', 'N/A')}%</p>
                        <p><strong>Wind Speed:</strong> {weather.get('wind_speed', 'N/A')} m/s</p>
                    </div>
                    <p style="text-align: center; color: #00e5ff99;">Generated by JARVIS Weather System</p>
                </div>
            </body>
        </html>
        """
        
        return self.send_email(to, "🌤️ Weather Report", html, is_html=True)


if __name__ == "__main__":
    # Test
    try:
        manager = EmailManager()
        print("[EMAIL] Manager initialized successfully")
    except Exception as e:
        print(f"Error: {e}")
